FROM goland:1.17.5
ARG version

COPY go.* /go/src/github.com/stebennett/squad-dashboard
COPY pkg/ /go/src/github.com/stebennett/squad-dashboard/pkg/
COPY vendor/ /go/src/github.com/stebennett/squad-dashboard/vendor
COPY cmd/datadashboard/ /go/src/github.com/stebennett/cmd/datadashboard/
WORKDIR /go/src/github.com/stebennett/cmd/datadashboard/
RUN GO111MODULE=on GOFLAGS=-mod=vendor CGO_ENABLED=0 GOOS linux go build -v -ldflags "-X github.com/stebennett/squad-dashboard/cmd/datadashboard/main.version=$version" -a -installsuffix cgo -o datadashboard .

FROM apline:3.14
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=0 /go/src/github.com/stebennett/squad-dashboard/cmd/datadashboard .
ENTRYPOINT ["/app/datadashboard"]
CMD ["run", "--logtostderr"]
