#!/usr/bin/env bash

set -e

display_usage() {
  cat <<EOM
    ##### wait_for_postgres #####
    Waits for postgres to be running before running migrations
EOM
}

print_error() {
  message="*********** [ $1 ] ***********"
  echo ""
  echo "$message"
  echo ""
}

validate_var() {
  if [[ -z $2 ]]; then
    print_error "$1 is required"
    display_usage
    exit 1
  fi
}

while [[ $# > 0 ]]; do
  key="$1"

  case ${key} in
    -h|--host)
      host=$2
      shift
      ;;
    -d|--database)
      database=$2
      shift
      ;;
    -u|--username)
      username=$2
      shift
      ;;
    -p|--password)
      password=$2
      shift
      ;;
    -c|--command)
      shift
      cmd="$@"
      ;;
  esac
  shift
done

validate_var '-h | --host' ${host}
validate_var '-d | --database' ${database}
validate_var '-u | --username' ${username}
validate_var '-p | --password' ${password}
validate_var '-c | --command' ${cmd}

until PGPASSWORD=$password psql -h "$host" -U "$username" -d "$database" -c '\l'; do
  >&2 echo "Postgres is unavailable - sleeping"
  sleep 1
done

>&2 echo "Postgres is up - executing command"
exec $cmd
